import type { ChartConfigType } from '../types'
import type { InteractActionItem } from '../types/events'

export type ComponentDefinition = ChartConfigType & {
  name: string
  icon: string
  defaultOption: Record<string, any>
  defaultProps: Record<string, any>
  defaultInteractActions?: InteractActionItem[]
}

const chartInteractActions: InteractActionItem[] = [
  {
    interactType: 'setFilter',
    interactName: '数据筛选',
    componentEmitEvents: {},
  },
  {
    interactType: 'clearFilter',
    interactName: '清除筛选',
    componentEmitEvents: {},
  },
  {
    interactType: 'setRequestConfig',
    interactName: '修改请求配置',
    componentEmitEvents: {},
  },
  {
    interactType: 'clearOverrides',
    interactName: '清除交互参数',
    componentEmitEvents: {},
  },
  {
    interactType: 'setData',
    interactName: '设置数据',
    componentEmitEvents: {},
  },
]

const textInteractActions: InteractActionItem[] = [
  {
    interactType: 'setFilter',
    interactName: '数据筛选',
    componentEmitEvents: {},
  },
  {
    interactType: 'clearFilter',
    interactName: '清除筛选',
    componentEmitEvents: {},
  },
  {
    interactType: 'setRequestConfig',
    interactName: '修改请求配置',
    componentEmitEvents: {},
  },
  {
    interactType: 'setData',
    interactName: '设置数据',
    componentEmitEvents: {},
  },
]

export const componentDefinitions: ComponentDefinition[] = [
  {
    key: 'BarCommon',
    chartKey: 'VBarCommon',
    conKey: 'VCBarCommon',
    title: '柱状图',
    name: '柱状图',
    category: 'Bars',
    categoryName: '柱状图',
    package: 'Charts',
    chartFrame: 'echarts',
    image: 'bar.png',
    icon: '📊',
    defaultOption: {
      title: '柱状图',
      dataset: {
        dimensions: ['类别', '销量'],
        source: [
          ['一月', 120],
          ['二月', 200],
          ['三月', 150],
          ['四月', 80],
          ['五月', 70],
          ['六月', 110],
        ],
      },
    },
    defaultProps: {},
    defaultInteractActions: chartInteractActions,
  },
  {
    key: 'LineCommon',
    chartKey: 'VLineCommon',
    conKey: 'VCLineCommon',
    title: '折线图',
    name: '折线图',
    category: 'Lines',
    categoryName: '折线图',
    package: 'Charts',
    chartFrame: 'echarts',
    image: 'line.png',
    icon: '📈',
    defaultOption: {
      title: '折线图',
      dataset: {
        dimensions: ['月份', '访问量'],
        source: [
          ['一月', 820],
          ['二月', 932],
          ['三月', 901],
          ['四月', 1290],
          ['五月', 1330],
          ['六月', 1320],
        ],
      },
    },
    defaultProps: {},
    defaultInteractActions: chartInteractActions,
  },
  {
    key: 'PieCommon',
    chartKey: 'VPieCommon',
    conKey: 'VCPieCommon',
    title: '饼图',
    name: '饼图',
    category: 'Pies',
    categoryName: '饼图',
    package: 'Charts',
    chartFrame: 'echarts',
    image: 'pie.png',
    icon: '🥧',
    defaultOption: {
      title: '饼图',
      dataset: {
        dimensions: ['类别', '数量'],
        source: [
          ['搜索引擎', 1048],
          ['社交媒体', 735],
          ['直接访问', 580],
          ['邮件营销', 484],
          ['联盟广告', 300],
        ],
      },
    },
    defaultProps: {},
    defaultInteractActions: chartInteractActions,
  },
  {
    key: 'ScrollList',
    chartKey: 'VScrollList',
    conKey: 'VCScrollList',
    title: '滚动列表',
    name: '滚动列表',
    category: 'Lists',
    categoryName: '列表',
    package: 'HTML',
    chartFrame: 'common',
    image: 'scroll.png',
    icon: '📜',
    defaultOption: {
      dataset: {
        dimensions: ['排名', '名称', '数值', '状态'],
        source: [
          ['1', '搜索引擎', '1,048', '↑ 12%'],
          ['2', '社交媒体', '735', '↑ 8%'],
          ['3', '直接访问', '580', '↓ 3%'],
          ['4', '邮件营销', '484', '↑ 5%'],
          ['5', '联盟广告', '300', '↓ 1%'],
          ['6', '视频广告', '250', '↑ 15%'],
          ['7', '博客文章', '180', '↑ 22%'],
          ['8', '新闻资讯', '120', '↓ 5%'],
        ],
      },
    },
    defaultProps: {
      scrollSpeed: 30,
      visibleRows: 5,
      rowHeight: 36,
      showHeader: true,
      headerBg: '#313244',
      headerColor: '#cdd6f4',
      zebraOdd: '#1e1e2e',
      zebraEven: '#181825',
      fontSize: 13,
      textColor: '#cdd6f4',
      highlightColor: '#89b4fa',
    },
  },
  {
    key: 'HeilongjiangMap',
    chartKey: 'VHeilongjiangMap',
    conKey: 'VCHeilongjiangMap',
    title: '黑龙江地图',
    name: '黑龙江地图',
    category: 'Maps',
    categoryName: '地图',
    package: 'Charts',
    chartFrame: 'echarts',
    image: 'map.png',
    icon: '🗺️',
    defaultOption: {
      title: '黑龙江省地图',
      dataset: {
        dimensions: ['城市', '数值'],
        source: [
          ['哈尔滨市', 150],
          ['齐齐哈尔市', 80],
          ['牡丹江市', 90],
          ['佳木斯市', 70],
          ['大庆市', 120],
          ['鸡西市', 60],
          ['双鸭山市', 50],
          ['伊春市', 40],
          ['七台河市', 30],
          ['鹤岗市', 35],
          ['黑河市', 45],
          ['绥化市', 75],
          ['大兴安岭地区', 25],
        ],
      },
    },
    defaultProps: {},
    defaultInteractActions: chartInteractActions,
  },
  {
    key: 'TextDisplay',
    chartKey: 'VTextDisplay',
    conKey: 'VCTextDisplay',
    title: '文本组件',
    name: '文本组件',
    category: 'Texts',
    categoryName: '文本',
    package: 'HTML',
    chartFrame: 'common',
    image: 'text.png',
    icon: '📝',
    defaultOption: {
      title: '文本内容',
      dataset: {
        dimensions: ['字段1', '字段2'],
        source: [['示例值1', '示例值2']],
      },
    },
    defaultProps: {
      text: '文本内容',
      fontSize: 32,
      fontWeight: 'bold',
      textAlign: 'center',
      colorMode: 'solid',
      textColor: '#cdd6f4',
      gradientStart: '#89b4fa',
      gradientEnd: '#cba6f7',
      gradientDirection: 'to right',
      bgColor: 'transparent',
      lineHeight: 1.5,
      letterSpacing: 0,
      padding: 12,
      subText: '',
      subFontSize: 16,
      subFontWeight: 'normal',
      subTextColor: '#a6adc8',
      subTextAlign: 'center',
      subLineHeight: 1.5,
      textDefault: '',
      subTextDefault: '',
    },
    defaultInteractActions: textInteractActions,
  },
  {
    key: 'BackgroundCard',
    chartKey: 'VBackgroundCard',
    conKey: 'VCBackgroundCard',
    title: '背景卡片',
    name: '背景卡片',
    category: 'Containers',
    categoryName: '容器',
    package: 'HTML',
    chartFrame: 'common',
    image: 'bgcard.png',
    icon: '📦',
    defaultOption: {
      title: '标题',
    },
    defaultProps: {
      cardWidth: 900,
      cardHeight: 900,
      cardBgColor: '#ffffff',
      cardBorderRadius: 16,
      cardBorderColor: '#e8ecf1',
      cardBorderWidth: 1,
      cardShadow: '0 2px 12px rgba(0,0,0,0.06)',
      cardPadding: '40px 48px',
      titleText: '标题',
      titleFontSize: 32,
      titleFontWeight: 600,
      titleColor: '#1d2a3a',
      titleLineHeight: 1.3,
      showDecorator: true,
      decoratorColor: '#e34d59',
      decoratorWidth: 6,
      decoratorHeight: 32,
      decoratorRadius: 3,
      showSubtitle: false,
      subText: '',
      subFontSize: 16,
      subColor: '#8c9aa8',
      subMarginTop: 8,
      subPaddingLeft: 20,
    },
    defaultInteractActions: [],
  },
  {
    key: 'RiskScrollList',
    chartKey: 'VRiskScrollList',
    conKey: 'VCRiskScrollList',
    title: '业务滚动列表',
    name: '业务滚动列表',
    category: 'Lists',
    categoryName: '列表',
    package: 'HTML',
    chartFrame: 'common',
    image: 'riskscroll.png',
    icon: '📋',
    defaultOption: {
      dataset: {
        dimensions: ['公司名称', '风险等级', '风险类型', '时间', '备注'],
        source: [
          ['哈尔滨贯庄典当有限责任公司', '高', '经营异常', '01-12 08:11', ''],
          ['哈尔滨市金龙典当有限责任公司', '高', '超比例放款', '03-10 14:43', ''],
          ['哈尔滨市靖宇典当有限责任公司', '危', '经营异常', '03-26 09:18', ''],
          ['哈尔滨市鑫瑞龙典当有限责任公司', '中', '司法信用风险', '02-27 11:08', '逾期90天以上贷款'],
          ['哈尔滨天翼典当有限责任公司', '高', '经营异常', '06-21 08:35', ''],
          ['黑龙江鼎信典当有限公司', '—', '资本充足率偏离度', '—', ''],
        ],
      },
    },
    defaultProps: {
      bgColor: '#ffffff',
      borderRadius: 12,
      borderColor: '#e8ecf1',
      shadow: '0 1px 4px rgba(0,0,0,0.04)',
      maxHeight: 500,
      containerPaddingTop: 0,
      containerPaddingRight: 0,
      containerPaddingBottom: 0,
      containerPaddingLeft: 0,
      itemPadding: '16px 24px',
      itemBorderColor: '#f0f2f5',
      itemBorderWidth: 1,
      itemBorderRadius: 0,
      itemGap: 0,
      itemHoverBg: '#fafbfc',
      useZebra: false,
      itemBgColor: '#ffffff',
      itemBgOdd: '#fafbfc',
      itemBgEven: '#ffffff',
      dotSize: 10,
      dotHighColor: '#e34d59',
      dotCriticalColor: '#c62828',
      dotMediumColor: '#e67e22',
      dotDefaultColor: '#b0bec5',
      nameFontSize: 15,
      nameFontWeight: 600,
      nameColor: '#1d2a3a',
      badgeHighBg: '#fef0f0', badgeHighColor: '#e34d59', badgeHighBorder: '#fcd4d4',
      badgeCriticalBg: '#ffebee', badgeCriticalColor: '#c62828', badgeCriticalBorder: '#ffcdd2',
      badgeMediumBg: '#fff3e0', badgeMediumColor: '#e67e22', badgeMediumBorder: '#fde4c8',
      badgeDefaultBg: '#f0f2f5', badgeDefaultColor: '#5a6a7a', badgeDefaultBorder: '#e0e4ea',
      riskTypes: [
        { name: '经营异常', color: '#e34d59' },
        { name: '超比例放款', color: '#e67e22' },
        { name: '司法信用风险', color: '#c62828' },
        { name: '资本充足率偏离度', color: '#8c9aa8' },
      ],
      typeTagBg: '#f4f6f9',
      typeTagColor: '#8c9aa8',
      subFontSize: 13,
      subColor: '#6b7a8a',
      timeColor: '#8c9aa8',
      showFooter: true,
      footerBg: '#fafbfc',
      footerColor: '#8c9aa8',
      footerFontSize: 13,
      footerAlign: 'right',
      scrollSpeed: 30,
      visibleRows: 5,
    },
    defaultInteractActions: [],
  },
  {
    key: 'ImageDisplay',
    chartKey: 'VImageDisplay',
    conKey: 'VCImageDisplay',
    title: '图片组件',
    name: '图片组件',
    category: 'Texts',
    categoryName: '文本',
    package: 'HTML',
    chartFrame: 'common',
    image: 'image.png',
    icon: '🖼️',
    defaultOption: {
      dataset: '',
    },
    defaultProps: {
      imageScale: 'cover',
      borderRadius: 0,
      opacity: 1,
      borderWidth: 0,
      borderColor: '#45475a',
      bgColor: 'transparent',
    },
    defaultInteractActions: [],
  },
]
